### ISSUE TITLE
http error 400 on ios

### ISSUE THREAD

**Issue by cpo81** [linuxserver/docker-tvheadend#81] opened 2018-03-22 07:32 UTC
Hi,

docker container seems to work well, great work done.

However the ios clients do have a problem, I get bad request 400 on the client.
With http Browser the access and watching is working

Here the logs, the ip in the logs is the client ip

2018-03-22 07:23:33.230 http: 10.33.0.110: HTTP/1.1 POST (3) /api/channeltag/grid -- 400
2018-03-22 07:23:33.230 http: 10.33.0.110: HTTP/1.1 GET (1) /api/serverinfo -- 400
2018-03-22 07:23:33.230 http: 10.33.0.110: HTTP/1.1 POST (3) /api/channel/grid -- 400
2018-03-22 07:23:33.231 http: 10.33.0.110: HTTP/1.1 GET (1) /api/status/subscriptions -- 400
2018-03-22 07:23:33.260 http: 10.33.0.110: HTTP/1.1 GET (1) /api/mpegts/network/grid?limit=99999999 -- 400
2018-03-22 07:23:33.261 http: 10.33.0.110: HTTP/1.1 GET (1) /api/status/inputs -- 400
2018-03-22 07:23:33.261 http: 10.33.0.110: HTTP/1.1 GET (1) /api/mpegts/mux/grid?limit=99999999 -- 400
2018-03-22 07:23:33.261 http: 10.33.0.110: HTTP/1.1 GET (1) /api/mpegts/service/grid?limit=99999999 -- 400
2018-03-22 07:23:33.295 http: 10.33.0.110: HTTP/1.1 GET (1) /api/profile/list -- 400
2018-03-22 07:23:33.306 http: 10.33.0.110: HTTP/1.1 GET (1) /config?op=loadSettings -- 400
2018-03-22 07:23:33.306 http: 10.33.0.110: HTTP/1.1 POST (3) /api/idnode/load -- 400
2018-03-22 07:23:33.306 http: 10.33.0.110: HTTP/1.1 POST (3) /api/channeltag/grid -- 400
2018-03-22 07:23:33.314 http: 10.33.0.110: HTTP/1.1 GET (1) /extjs.html -- 400
2018-03-22 07:23:34.267 http: 10.33.0.110: HTTP/1.1 POST (3) /comet/poll -- 400
2018-03-22 07:23:35.249 http: 10.33.0.110: HTTP/1.1 POST (3) /comet/poll -- 400
2018-03-22 07:23:36.231 http: 10.33.0.110: HTTP/1.1 POST (3) /comet/poll -- 400
2018-03-22 07:23:37.227 http: 10.33.0.110: HTTP/1.1 POST (3) /comet/poll -- 400
2018-03-22 07:23:38.233 http: 10.33.0.110: HTTP/1.1 POST (3) /comet/poll -- 400
2018-03-22 07:23:39.229 http: 10.33.0.110: HTTP/1.1 POST (3) /comet/poll -- 400

**Comment by tobbenb** [comment] 2018-03-22 12:55
Which tag do you use for the container?
Might be a problem with the client you use.

**Comment by cpo81** [comment] 2018-03-22 17:05
Thanks for the reply, I use "latest"

**Comment by vistalba** [comment] 2018-03-22 19:09
Same issue here with TVHclient and also plexheadend. Both worked before.

It looks like the problem is user:pass in the URL. ( http://user:pass@server:9981)

**Comment by vistalba** [comment] 2018-03-22 22:04
@cpo81 are you using kubernetes?

**Comment by cpo81** [comment] 2018-03-22 22:05
no, docker run on ubuntu

here’s my startup command

sudo docker run --detach \
    --name tv.domain.net<http://tv.domain.net> \
    --net=host \
    --restart always \
    --volume /srv/tvheadend/config:/config \
    --volume /srv/tvheadend/recordings:/recordings \
    --volume /srv/tvheadend/picons:/picons \
    -e PGID=1001 -e PUID=1001 \
    linuxserver/tvheadend:latest

On 22.03.2018, at 23:04, vistalba <notifications@github.com<mailto:notifications@github.com>> wrote:


@cpo81<https://github.com/cpo81> are you using kubernetes?

**Comment by vistalba** [comment] 2018-03-23 09:45
Okay... I think I found a solution for my problems. (TVHClient and plexheadend). 

Check your tvheadend server configuration:

General -> Base -> Authentication Type = Both plain and digest (Look at screenshot).

As I understood this is new in tvheadend 4.3

![image](https://user-images.githubusercontent.com/12324196/37822506-f54be9b8-2e86-11e8-9263-75dab31ca9ef.png)

**Comment by cpo81** [comment] 2018-03-23 10:22
Yes!!!
That did the trick
Thank you very much
Works perfectly now

On 23.03.2018, at 10:45, vistalba <notifications@github.com<mailto:notifications@github.com>> wrote:


Okay... I think I found a solution for my problems. (TVHClient and plexheadend).

Check your tvheadend server configuration:

General -> Base -> Authentication Type = Both plain and digest (Look at screenshot).

As I understood this is new in tvheadend 4.3

[image]<https://user-images.githubusercontent.com/12324196/37822506-f54be9b8-2e86-11e8-9263-75dab31ca9ef.png>

**Comment by sparklyballs** [comment] 2018-03-23 10:25
can you close the issue @cpo81 if you're happy it's resolved

**Closed** 2018-03-23 10:26 UTC
