### ISSUE TITLE
xmltv.sock issue

### ISSUE THREAD

**Issue by DOFfactory** [linuxserver/docker-tvheadend#163] opened 2020-04-12 09:30 UTC
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior
Whenever I recreate/update the container, the socket under `config/epggrab/xmltv.sock` should be recreated to receive connection from tvheadend and other epg grabbers that support it

## Current Behavior
Whenever I restart/recreate/update the container, the `xmltv.sock` becomes a folder somehow, and other epg grabbers cannot connect

## Steps to Reproduce

1. create tvheadend container
2. enable the epggrab module
3. link it with an epggrabber (webgrabplus, easyepg)
4. restart the tvheadend container
5. other epg grabbers cannot connect to `xmltv.sock` anymore, and it appears under linux as a folder
6. the following commands solve this issue
```
admin $ rm -rf /docker/tvheadend/config/epggrab/xmltv.sock
admin $ touch /docker/tvheadend/config/epggrab/xmltv.sock
```

## Environment
**OS: Linux**      
**CPU architecture:** x86_64     
**How docker service was installed:**      
Does not matter. 

My guess is that in the docker creation script additional lines need to be introduced, which check for the presence of `xmltv.sock` and if it throws TRUE, it should be deleted and a file should be recreated

**Comment by tobbenb** [comment] 2020-04-12 10:14
What do you mean in point 3 by link it with an epg grabber?
Enabling the external grabber and restarting the tvheadend container does not convert the xmlt.sock into a folder here.
Please provide exact steps to reproduce the error. As of now it's missing the part where you send something to the xmltv.sock.

You do know that you have both a xmltv file grabber and webgrab++ file grabber you can use to get the epg data into tvheadend?

**Comment by tobbenb** [comment] 2020-04-19 12:02
Closing this as I can't reproduce the issue and no reply.

**Closed by tobbenb** 2020-04-19 12:02 UTC

**Comment by chkuendig** [comment] 2023-11-26 13:23
Ticket can remain closed, but FWIW: I just observed the same thing but can't reproduce it anymore once I deleted the erroneous folder. I think it was related to my migration from the non-dockerized tvheadend.
